build:
  image: maven:3.8.5-openjdk-18
  stage: build
  script:
    - mvn jar:jar
  artifacts:
    when: always
    paths:
      - target/*.jar

test:
  image: maven:3.8.5-openjdk-18
  stage: test
  script:
    - mvn surefire:test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
