# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- build
sast:
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, eslint, flawfinder, gosec, kubesec,
      nodejs-scan, phpcs-security-audit, pmd-apex, security-code-scan, semgrep, sobelow
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

build:
  image: maven:3.8.5-openjdk-18
  stage: build
  tags:
  - pppp
  script:
  - mvn jar:jar
  artifacts:
    when: always
    paths:
    - target/*.jar
test:
  image: maven:3.8.5-openjdk-18
  stage: test
  tags:
  - pppp
  script:
  - mvn test
  artifacts:
    when: always
    reports:
      junit:
      - target/surefire-reports/TEST-*.xml
